package LexicalAnalyse;

public enum TokenType {
    ID("id"),
    INT_NUM("intnum"),
    FLOAT_NUM("floatnum"),
    INVALID_NUM("invalidnum"),
    INVALID_ID("invalidid"),
    INVALID_CHAR("invalidchar"),
    PLUS("plus"),
    MINUS("minus"),
    MULT("mult"),
    DIV("div"),
    SEMI("semi"),
    COMMA("comma"),
    DOT("dot"),
    EQ("eq"),
    RE_TYPE("returntype"),
    ASSIGN("assign"),
    LT("lt"),
    LEQ("leq"),
    NOT_EQ("noteq"),
    GT("gt"),
    GEQ("geq"),
    COLON("colon"),
    SCOPEOP("scopeop"),
    OP_PAR("openpar"),
    CL_PAR("closepar"),
    OP_CUBR("opencubr"),
    CL_CUBR("closecubr"),
    OP_SQBR("opensqbr"),
    CL_SQBR("closesqbr"),
    IN_CMT("inlinecmt"),
    BK_CMT("blockcmt"),
    INVALID_CMT("invalidcmt"),
    AND("and"),
    OR("or"),
    NOT("not"),
    INTEGER("integer"),
    FLOAT("float"),
    VOID("void"),
    CLASS("class"),
    SELF("self"),
    ISA("isa"),
    WHILE("while"),
    IF("if"),
    THEN("then"),
    ELSE("else"),
    READ("read"),
    WRITE("write"),
    RETURN("return"),
    LOCAL_VAR("localvar"),
    CONSTRUCTOR("constructor"),
    ATTRIBUTE("attribute"),
    FUNCTION("function"),
    PUBLIC("public"),
    PRIVATE("private");
    public final String tokenTypeStr;
    private TokenType(String tokenTypeStr) {
        this.tokenTypeStr = tokenTypeStr;
    }
}
